OAI-16: Added PUT method to claimResponse endpoint
openimis/openimis-be-api_fhir_r4_py pull request #1
Opened 2020-11-16 12:32 UTC by dborowiecki

Ticket: [OAI-16](https://openimis.atlassian.net/browse/OAI-16)

2020-11-16 16:41 UTC, delcroip approved these changes

2020-11-17 12:37 UTC, dragos-dobre requested changes

2020-11-18 09:39 UTC, dborowiecki commented on api_fhir_r4/converters/claimResponseConverter.py
>                      cls.build_codeable_concept(2, text="entered")
Method refactored

2020-11-18 10:12 UTC, dragos-dobre approved these changes

2020-11-18 10:12 UTC, merged