OE0-32: added new extensions, update existing and remove not used in profile
openimis/openimis-be-api_fhir_r4_py pull request #30
Opened 2021-07-27 09:57 UTC by sniedzielski

TICKET: https://openimis.atlassian.net/browse/OE0-32

- Adding new extensions
- updating contact with adding displat/code and fixing URL. 
- Removing extensions not used like ValidityFrom, Poverty etc
- uppdate crating build_imis_extension and build_imis_address

2021-07-27 14:52 UTC, dragos-dobre requested changes

2021-07-27 14:52 UTC, dragos-dobre commented on api_fhir_r4/mapping/patientMapping.py
> +    education_level = {
Get the list from DB.

2021-07-27 14:52 UTC, dragos-dobre commented on api_fhir_r4/mapping/patientMapping.py
> +    patient_profession = {
Get the list from DB.

2021-07-27 14:52 UTC, dragos-dobre commented on api_fhir_r4/mapping/patientMapping.py
> +    identification_type = {
Get the list from DB.

2021-07-30 08:20 UTC, sniedzielski commented on api_fhir_r4/mapping/patientMapping.py
> +    education_level = {
fixed

2021-07-30 08:20 UTC, sniedzielski commented on api_fhir_r4/mapping/patientMapping.py
> +    patient_profession = {
fixed

2021-07-30 08:20 UTC, sniedzielski commented on api_fhir_r4/mapping/patientMapping.py
> +    identification_type = {
fixed

2021-07-30 12:09 UTC, dragos-dobre requested changes

2021-07-30 12:09 UTC, dragos-dobre commented on api_fhir_r4/mapping/patientMapping.py
Get the list from DB.

2021-07-30 12:11 UTC, sniedzielski commented on api_fhir_r4/mapping/patientMapping.py
ok

2021-07-30 12:20 UTC, sniedzielski commented on api_fhir_r4/mapping/patientMapping.py
fixed

2021-07-30 14:03 UTC, dragos-dobre approved these changes

2021-07-30 14:03 UTC, merged