E0-10: Code identifiers recognition for viewsets resources
openimis/openimis-be-api_fhir_r4_py pull request #35
Opened 2021-08-04 09:56 UTC by dborowiecki

TICKET: [E0-10](https://openimis.atlassian.net/browse/OE0-10)

Additional changes: 
- Views moved from single .py file to submodule. 
- Minor changes in conventers  to fix resource-related bugs

2021-08-04 11:00 UTC, delcroip requested changes

2021-08-04 11:59 UTC, dborowiecki commented on api_fhir_r4/converters/claimResponseConverter.py
> +        if imis_claim.status == 16 and approved:
Done, changed also for other status codes.

2021-08-04 12:03 UTC, dborowiecki commented on api_fhir_r4/mixins.py
> +        raise Http404
Added, due to how OperationOutcome handle exceptions it was not used and "not-found" message was displayed in every case. I changed OperationOutcome conventer, now 404 error message is passed in http response details.

2021-08-06 11:02 UTC, delcroip approved these changes

2021-08-06 11:03 UTC, merged